repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: double-quote-string-fixer
    - id: trailing-whitespace
-   repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
    - id: docformatter
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    - id: flake8